### ISSUE TITLE
Add ROBOT tests and Travis

### ISSUE THREAD

**Issue by jamesaoverton** [IEDB/MRO#16]
We're seeing too many small problems with our builds. Please add some ROBOT quality control tests and run them with Travis.

**Comment by beckyjackson** [comment]
Do we want to run `robot report`? That would catch if a duplicate label was added. The only problem is it currently fails because MRO has no license. We could just make our own `profile.txt`

Also, I was thinking a python script to validate no duplicates in `iedb.tsv`, since these are not used in `mro.owl`?

**Comment by rvita** [comment]
license should be License CC-BY?

**Comment by beckyjackson** [comment]
@rvita - yeah, it's in the OWL file, but it uses the wrong property, so ROBOT reported it as an error.

**Comment by jamesaoverton** [comment]
Yes, please run `robot report`. A Python script to check for duplicates is fine. SPARQL is also fine.

**Comment by jamesaoverton** [comment]
Fixed by #18
